spring.application.name=n5student-grade-management-system
spring.datasource.url=jdbc:mysql://localhost:3306/n5sgms?useSSL=false&serverTimezone=UTC&useLegacyDateTimeCode=false
spring.datasource.username=root
spring.datasource.password=2634
spring.jpa.hibernate.ddl-auto=update
logging.level.org.hibernate.SLQ=DEBUG
server.port=8090